sixfeetup/scaf

- {{cookiecutter.project_slug}}/docs/README.md
This directory was added as an incentive (and reminder) for everyone involved in the project, to start adding more documentation.
This was discussed in a REPL Alliance Crew L10.
> Create docs directory inside project template

- .pre-commit-config.yaml
- docs/pre-commit-docs
- docs/pre-commit.md
Create pre-commit-config.yml file.
Document pre-commit file.
> Added pre-commit script and its documentation.

- {{cookiecutter.project_slug}}/backend/requirements/base.in
> fix: pin urllib3. Fixes #60

- {{cookiecutter.project_slug}}/README.md
- {{cookiecutter.project_slug}}/Tiltfile
This PR adds support for developing against a Kubernetes cluster using Tilt. See https://tilt.dev/ for more info.
> feat: add Tilt support. Close #58

- {{cookiecutter.project_slug}}/terraform/modules/application/acm.tf
- {{cookiecutter.project_slug}}/terraform/modules/application/cloudfront.tf
- {{cookiecutter.project_slug}}/terraform/modules/application/data.tf
- {{cookiecutter.project_slug}}/terraform/modules/application/route53.tf
- {{cookiecutter.project_slug}}/terraform/modules/application/variables.tf
- {{cookiecutter.project_slug}}/terraform/prod/application.tf
- {{cookiecutter.project_slug}}/terraform/prod/variables.tf
- {{cookiecutter.project_slug}}/terraform/sandbox/application.tf
- {{cookiecutter.project_slug}}/terraform/sandbox/variables.tf
Add cloudfront to terraform/modules where it can be used by sandbox and prod
> Add cloudfront CDN

- {{cookiecutter.project_slug}}/k8s/base/django.yaml
- {{cookiecutter.project_slug}}/k8s/base/ingress.yaml
- {{cookiecutter.project_slug}}/k8s/base/react.yaml
- {{cookiecutter.project_slug}}/k8s/prod/certificate.yaml
- {{cookiecutter.project_slug}}/k8s/sandbox/certificate.yaml
- {{cookiecutter.project_slug}}/terraform/ec2-cluster/Makefile
- {{cookiecutter.project_slug}}/terraform/ec2-cluster/README.md
- {{cookiecutter.project_slug}}/terraform/ec2-cluster/config.yml
Install cert manager in cluster
Use ingress-route for routes
Add certificates for routes
Close #70
> Add cert manager

- {{cookiecutter.project_slug}}/backend/requirements/production.in
- {{cookiecutter.project_slug}}/backend/requirements/tests.in
- {{cookiecutter.project_slug}}/k8s/prod/kustomization.yaml
- {{cookiecutter.project_slug}}/k8s/prod/patches.yaml
- {{cookiecutter.project_slug}}/k8s/sandbox/kustomization.yaml
- {{cookiecutter.project_slug}}/k8s/sandbox/patches.yaml
Add daphne to requirements
Add patch so daphne command runs in prod and sandbox
Closes #71
> Add daphne

- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/docker-compose.yml
Problem description:
https://discuss.circleci.com/t/postgres-container-failing-with-initdb-error-program-postgres-is-needed-by-initdb-but-was-not-found/48470
> Fix image of PostgreSQL

- .pre-commit-config.yaml
- {{cookiecutter.project_slug}}/.github/workflows/main.yaml
- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/backend/config/asgi.py
- {{cookiecutter.project_slug}}/backend/config/settings/local.py
- {{cookiecutter.project_slug}}/backend/requirements/tests.in
- {{cookiecutter.project_slug}}/bitbucket-pipelines.yml
- {{cookiecutter.project_slug}}/docker-compose.yml
Update Github Actions and Bitbucket Pipelines to run all backend tests in the pipelines.
Part of development of #73
> CI pipelines backend test

- cookiecutter.json
- hooks/post_gen_project.py
- {{cookiecutter.project_slug}}/.envrc
- {{cookiecutter.project_slug}}/README.md
- {{cookiecutter.project_slug}}/backend/config/settings/base.py
- {{cookiecutter.project_slug}}/backend/requirements/base.in
- {{cookiecutter.project_slug}}/frontend/Dockerfile
- {{cookiecutter.project_slug}}/frontend/package-lock.json
- {{cookiecutter.project_slug}}/frontend/package.json
- {{cookiecutter.project_slug}}/frontend/src/.env.example
- {{cookiecutter.project_slug}}/frontend/src/main.tsx
- {{cookiecutter.project_slug}}/k8s/base/django.configmap.yaml
> feat: make sentry optional (close #177)

- {{cookiecutter.project_slug}}/Tiltfile
- {{cookiecutter.project_slug}}/frontend/vite.config.ts
- {{cookiecutter.project_slug}}/k8s/base/celery.yaml
- {{cookiecutter.project_slug}}/k8s/base/django.yaml
- {{cookiecutter.project_slug}}/k8s/base/mailhog.yaml
- {{cookiecutter.project_slug}}/k8s/base/postgres.yaml
- {{cookiecutter.project_slug}}/k8s/base/react.yaml
- {{cookiecutter.project_slug}}/k8s/base/redis.yaml
- {{cookiecutter.project_slug}}/k8s/prod/patches.yaml
- {{cookiecutter.project_slug}}/k8s/sandbox/patches.yaml
PR to use consistent labeling for Kubernetes services and deployments.
> chore: fix k8s labels

- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/README.md
- {{cookiecutter.project_slug}}/Tiltfile
PR to remove obsolete Docker Makefile targets and replace with alternatives that run against the local k8s cluster.
> chore: remove docker

- .envrc
- .gitignore
- README.md
- flake.lock
- flake.nix
This PR adds a Nix Flake for development on Scaf. See the updates to the README in this PR for more information.
> feat: add Nix Flake for development on Scaf

- {{cookiecutter.project_slug}}/frontend/__tests__/about.test.tsx
- {{cookiecutter.project_slug}}/frontend/package-lock.json
- {{cookiecutter.project_slug}}/frontend/package.json
- {{cookiecutter.project_slug}}/frontend/vitest.config.ts
**Overview**
* Adds vitest dependencies
* Adds basic test for about page
* Updates scripts "lint" -> "lint-src" to follow same convention with the makefile
* Adds "typecheck" script for CI/CD
**Visuals**
> Adds vitest dependencies and test

- {{cookiecutter.project_slug}}/backend/config/settings/base.py
- {{cookiecutter.project_slug}}/backend/config/settings/local.py
- {{cookiecutter.project_slug}}/backend/config/settings/production.py
- {{cookiecutter.project_slug}}/backend/requirements/base.in
> Add django-cors-headers

- {{cookiecutter.project_slug}}/k8s/local/postgres.yaml
> feat: upgrade to postgres 16

- .github/workflows/setup-project.yaml
- install.sh
A new function 'check_top_level_dependencies' has been added to the install.sh script. This function checks for the existence of all top-level dependencies. If any required dependencies are missing, the function alerts the user and provides instructions for installation on different operating systems.
The check for top-level dependencies is now being conducted at the start of the installation process.
> feat: add function to check for necessary dependencies in install.sh

- {{cookiecutter.project_slug}}/backend/requirements/local.in
otherwise local.txt comes out wrong
> fix: local.txt should include stuff from base

- {{cookiecutter.project_slug}}/frontend/.eslintrc.json
- {{cookiecutter.project_slug}}/frontend/README.md
- {{cookiecutter.project_slug}}/frontend/__tests__/about.test.tsx
- {{cookiecutter.project_slug}}/frontend/lib/apolloClient.ts
- {{cookiecutter.project_slug}}/frontend/package-lock.json
- {{cookiecutter.project_slug}}/frontend/package.json
- {{cookiecutter.project_slug}}/frontend/pages/_app.tsx
- {{cookiecutter.project_slug}}/frontend/pages/about.tsx
- {{cookiecutter.project_slug}}/frontend/utils/test-utils.tsx
- {{cookiecutter.project_slug}}/frontend/vitest.config.ts
- {{cookiecutter.project_slug}}/frontend/vitest.setup.ts
**QA Steps:**
1. Create a scaf project
2. Cd into frontend folder
3. run `npm run test` and expect to see success (make sure `npm i` is run to install packages)
> fix: Fixes frontend tests

- README.md
- {{cookiecutter.project_slug}}/docs/sentry.md
> docs: update related to optional GraphQL

- README.md
- test-configs/nextjs-django-github.yaml
- test-scaf.sh
This PR adds a script to make it easy to test the cookiecutter part of Scaf while developing it. It incorporates the instructions @gfranxman added to the README and turns them into configurable options.
> feat: script to test cookiecutter part of Scaf

- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/k8s/templates/secrets.yaml.template
PR to:
* use `op inject` to create sealed secrets
* create common secrets target in Makefile
* add convenience targets to debug secrets for each environment
> feat: op inject secrets

- {{cookiecutter.project_slug}}/k8s/mailhog/mailhog.yaml
PR to fix mailhog port config.
> fix: mailhog port config (closes #249)

- scaf
Fix full stack template URL.
<details>
<summary>What the reviewer should check</summary>
| Check  | Description |
| ------------- | ------------- |
| :truck: **Diff size** | Is the PR small and focused, or should it be broken into smaller PRs?
| :test_tube: **Unit tests** | Are new features covered with appropriate unit tests?
| :lab_coat: **Acceptance Criteria met** | Are the Acceptance Criteria listed in the issue met?
| :monocle_face: **Code clarity** | Is the code easy to understand? Are variable and function names meaningful?
| :jigsaw: **Code organization** | Are files, modules, and functions structured logically?
| :carpentry_saw: **Conciseness** | Is the code free of unnecessary complexity or redundant code?
| :speech_balloon: **Comments & documentation** | Are code comments …
> fix: fullstack template url

- CHANGELOG.md
- package.json
* Update scaf to use copier and multiple templates (closes [#332](https://github.com/sixfeetup/scaf/issues/332), [#441](https://github.com/sixfeetup/scaf/issues/441), [#443](https://github.com/sixfeetup/scaf/issues/443), [#444](https://github.com/sixfeetup/scaf/issues/444), [#445](https://github.com/sixfeetup/scaf/issues/445)) ([ff3645a](https://github.com/sixfeetup/scaf/commit/ff3645a53b943c847130c4a49afbf7615b0b6a8c))
* Add VIRTUAL_ENV env variable for uv to work after latest upgrade… (fixes [#461](https://github.com/sixfeetup/scaf/issues/461)) ([c0f2c9a](https://github.com/sixfeetup/scaf/commit/c0f2c9aae8bc3f50898e57f613efc18c50b41452))
* fullstack template url ([c136fdb](https://github.com/sixfeetup/scaf/commit/c136fdb6f61813bceb1b4787968d4411afbbe946))
Ticket: #123
(Also in the …
> chore(release): 1.22.0 [skip ci]

- scaf
- test-scaf.sh
Ticket: #323, #324, #325 
Scaf was missing essential command options like uninstall, update, and help, which are standard in most tools for managing user experience
- Added uninstall option to allow users to remove the tool cleanly.
- Added update command to let users upgrade to the latest version easily.
- Introduced a help command to display usage instructions and available options.
<details>
<summary>What the reviewer should check</summary>
| Check  | Description |
| ------------- | ------------- |
| :truck: **Diff size** | Is the PR small and focused, or should it be broken into smaller PRs?
| :test_tube: **Unit tests** | Are new features covered with appropriate unit tests?
| :lab_coat: **Acceptance Criteria met** | Are the Acceptance Criteria listed in the issue met?
| …
> feat: add uninstall, upgrade and help options #323, #324. #325

- .github/workflows/semantic-release.yaml
Use GitHub deploy key for semantic release workflow.
> feat: Configure semantic-release workflow to use GitHub deploy key

- scaf
Ticket: #502
When no option was provided for template, the default option selected was AWS Lambda Template
🆕 What is changed by this PR?
- Fix the default option for scaf 
<details>
<summary>What the reviewer should check</summary>
| Check  | Description |
| ------------- | ------------- |
| :truck: **Diff size** | Is the PR small and focused, or should it be broken into smaller PRs?
| :test_tube: **Unit tests** | Are new features covered with appropriate unit tests?
| :lab_coat: **Acceptance Criteria met** | Are the Acceptance Criteria listed in the issue met?
| :monocle_face: **Code clarity** | Is the code easy to understand? Are variable and function names meaningful?
| :jigsaw: **Code organization** | Are files, modules, and functions structured logically?
| :carpentry_saw: …
> fix: Fix default template option #502
