README.md
{{cookiecutter.project_slug}}/backend/requirements/base.in

Added documentation of all base Python dependencies of the template. Tried to explain why the dependency is there and how it should be used. A reference for anyone starting to work with the template.
During the process of documenting the base dependencies in our template, I identified some libraries that shouldn't be in a base install of the project, or that are not top-level dependency (i.e. they are already installed when we include some other library). Some could be moved to `local.in` or `test.in` if we consider them really useful.
Removed libraries (and some reasoning):
- `astroid` - developer tool not used in the generated project
- `asttokens` - developer tool not used in the generated project
- `executing` - developer tool not used in the generated project
- `Faker` - testing …

Document base Python requirements

---

{{cookiecutter.project_slug}}/k8s/django.yaml

PR to run Django migrations as an init container. Fixes #51

feat: run migrations as init container

---

{{cookiecutter.project_slug}}/config/asgi.py
{{cookiecutter.project_slug}}/config/settings/base.py
{{cookiecutter.project_slug}}/config/settings/production.py
{{cookiecutter.project_slug}}/manage.py
{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/migrations/0001_initial.py

Change the existing template files so they match black and isort formatting. Doing this way, when the project is created, it won't require any new reformatting (that is done by a post hook for now)

Format template files to avoid need to reformat again

---

{{cookiecutter.project_slug}}/k8s/base/postgres.yaml

Add annotation to keep persistent volumes across tilt restarts.
Remove any references to named persistent volumes and use dynamic persistent volume provisioning. This works much more reliably with local Kubernetes dev environments like Docker Desktop and Kind. This is also the recommended way to provision storage in cloud agnostic way.

feat: keep PVs across tilt restart. closes #124

---

{{cookiecutter.project_slug}}/k8s/local/kustomization.yaml
{{cookiecutter.project_slug}}/k8s/local/secrets.yaml

This PR fixes the secrets-config not found error encountered when starting Tilt for local development.

fix: add secrets-config secret for local dev. close #175

---

{{cookiecutter.project_slug}}/.envrc
{{cookiecutter.project_slug}}/README.md
{{cookiecutter.project_slug}}/backend/config/settings/base.py
{{cookiecutter.project_slug}}/docs/sentry.md
{{cookiecutter.project_slug}}/frontend/src/main.tsx
{{cookiecutter.project_slug}}/k8s/base/app.configmap.yaml
{{cookiecutter.project_slug}}/k8s/base/celery.yaml
{{cookiecutter.project_slug}}/k8s/base/django.configmap.yaml
{{cookiecutter.project_slug}}/k8s/base/django.yaml
{{cookiecutter.project_slug}}/k8s/base/kustomization.yaml
{{cookiecutter.project_slug}}/k8s/base/postgres.cnpg.yaml
{{cookiecutter.project_slug}}/k8s/base/postgres.yaml
{{cookiecutter.project_slug}}/k8s/base/react.yaml
{{cookiecutter.project_slug}}/k8s/local/postgres.yaml
{{cookiecutter.project_slug}}/k8s/prod/kustomization.yaml
{{cookiecutter.project_slug}}/k8s/sandbox/kustomization.yaml

Also updated docs for the new local stack.
Seems like `.envrc` and `frontend/.env` / `frontend/src/.env.example` and documentation mentioning those could be removed.

Changes to correct requirement for sentry - #177 

---

{{cookiecutter.project_slug}}/README.md

For: https://github.com/sixfeetup/scaf/issues/234
Suggestion that user can type `s` to show running console output during tilt up.

Minor documentation tweak

---

{{cookiecutter.project_slug}}/k8s/local/postgres.yaml

PR to use dynamic volume provisioning for the Postres PVC. We shouldn't hardcode the storage class or the mount path. We should defer this to the cluster configuration.
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning

feat: use dynamic volume provisioning for postgres pvc

---

{{cookiecutter.project_slug}}/k8s/local/postgres.yaml

PR to ensure that the Postgres PV keeps its data across Tilt restarts

fix: keep postgres pvc across tilt restarts

---

.releaserc.json
package.json

This PR fixes the semantic release GH action to update the version inside package.json

fix: semantic release not updating version in package.json

---

{{cookiecutter.project_slug}}/README.md

We have a `repo_url` variable already in the cookie-cutter config so we might as well use it in the docs for the git clone command.

docs: use repo_url variable for git clone example

---

{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/Tiltfile
{{cookiecutter.project_slug}}/backend/Dockerfile
{{cookiecutter.project_slug}}/backend/config/settings/base.py
{{cookiecutter.project_slug}}/backend/requirements/base.in
{{cookiecutter.project_slug}}/backend/requirements/local.in
{{cookiecutter.project_slug}}/backend/requirements/production.in
{{cookiecutter.project_slug}}/backend/requirements/tests.in
{{cookiecutter.project_slug}}/bitbucket-pipelines.yml

This PR upgrades the Scaf template to the latest stable Django and Python versions.
Most importantly, I removed the pins in the *.in files to ensure that a newly generated project always has the latest Django version. This is not a cause for concern since running `make compile` after project creation will immediately pin all package versions. Additionally, this forces us to perform regular tests of Scaf-generated projects with the latest versions.
I tested the changes in the PR by creating a new project and verifying that both the frontend and backend sites work and that NextJS can make GraphQL queries against Django.

feat: upgrade django and python to latest stable versions

---

.github/workflows/setup-project.yaml
install.sh

- change `/usr/local/bin/` installation directory to a variable `PREFERRED_BIN_FOLDER` that defaults to `${HOME}/.local/bin`
- check folder existence and create it if necessary in `ensure_bin_folder` function
- check write permissions to bin folder and exit with warning if not writable
- validate if bin folder is in PATH, else exit with suggestion to add it
- ensure `kubectl`, `kind` and `scaf` tools are moved to the preferred bin folder
- make function `ensure_bin_folder` as first step at installation process.

feat: improve installation script to handle preferred bin folder

---

Dockerfile
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/backend/Dockerfile
{{cookiecutter.project_slug}}/backend/requirements/local.in

- Updated main Dockerfile to replace pip commands with uv pip.
- Modified backend Dockerfile to install uv and use it for managing pip packages.
- Adjusted Makefile to include uv for backend testing and package compilation.
- Removed pip-tools and pipdeptree from local requirements as part of the cleanup.
- implements #346

chore: update Dockerfiles and Makefile to use 'uv' for pip commands

---

scaf

- Updated the validation regex for project slugs to allow hyphens and underscores
- Added new variables, CLUSTER_SLUG and COOKIECUTTER_SLUG, to ensure compatibility with different systems
- Updated the 'kind create cluster' command to use CLUSTER_SLUG
- Changed the working directory to COOKIECUTTER_SLUG before executing make and git commands

feat: allow hyphens and underscores in project slugs

---

scaf

- This function celebrates successful project creation by simulating a 'party popper' animation.
- It also provides brief instructions on how to get started with the new project.
- This makes the user experience more interactive and enjoyable.
- The function is invoked after project creation and initial commit.
- Critical when the COOKIECUTTER process fails - user is still informed about the failure. Is there a sad-trombone emoji?

feat: add party_popper function to enhance project initiation experience

---

.github/workflows/setup-project.yaml
README.md
hooks/post_gen_project.py
install.sh
scaf

Added functionality to automatically configure git remote repositories to the scaf creation process.
This is done in the post_gen_project.py hook file using a new function called `configure_git_remote()`.  This function takes the repository URL built during the cookiecutter build out and initializes a new git repository in the new project directory.  It then sets the entered URL as the 'origin' remote.
Subsequently, removed the `git init .` statement from the scaf script since it now occurs in the `configure_git_remote()` function of the post_gen_project hook.
Also provided a detailed guide in README.md on how to test the cookiecutter portion of scaf.

feat: add automatic git remote configuration

---

.github/workflows/setup-project.yaml

buildkit cache
- Switched to Docker's build-push-action from version 2 to version 5 in the setup-project.yaml workflow file.
- Included context and file fields set to current directory and Dockerfile respectively.
- Added cache-from and cache-to fields with type=gha and mode=max to make use of GitHub's BuildKit cache for Docker builds.

feat: update docker build-push-action to v5 and utilize github's

---

.github/workflows/semantic-release.yaml

These changes are intended to allow the ci semantic release process to push its tags and changes from bumping the version back into the protected branch (main).
Example of such failure: https://github.com/sixfeetup/scaf/actions/runs/10490831281/job/29058471741

ci: semantic release failure workaround

---

{{cookiecutter.project_slug}}/k8s/base/django.yaml

Rearranged the order in which the environment variables are loaded in the Kubernetes configuration file for Django.
Environment variables will now be loaded from 'app-config' ConfigMap first, followed by the 'secrets-config'.
This allows the local secrets config to override the app-config and not the other way around.

feat: reorder environment variables in k8s django config

---

scaf

fix: Specify the full container path, including the host.

---

{{cookiecutter.project_slug}}/backend/config/settings/production.py
{{cookiecutter.project_slug}}/backend/{{cookiecutter.project_slug}}/utils/cloud_storage.py

- Changed DEFAULT_FILE_STORAGE and STATICFILES_STORAGE from local to S3 in production settings.
- Renamed utility 'storages.py' to 'cloud_storage.py'.
- Renamed classes in storage utility to reflect usage of S3 - 'StaticStorage' to 'S3StaticStorage' and 'MediaStorage' to 'S3MediaStorage'.
This was done primarily for clarity and to avoid name conflicts over the storages package.

feat: implement s3 storage for static and media files on production

---

install.sh

In the script, before the step to download and install 'scaf', a check if a file at the 'TEMP_DOWNLOAD' location exists.
If such a file does exist, it is removed before proceeding with the installation.

feat(install.sh): force re-download of Scaf on each install

---

.github/workflows/setup-project.yaml

Related to #381
Update GitHub action to build and push Docker images for both amd and arm architectures, and tag the latest build with 'latest'.
* **Build and push Docker image**: Update the `docker/build-push-action` step to build for both amd and arm architectures.
* **Tagging**: Add a new tag `sixfeetup/scaf:latest` to the `tags` field in the `docker/build-push-action` step.
* **Platforms**: Ensure the `platforms` field includes both `linux/amd64` and `linux/arm64`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/sixfeetup/scaf/issues/381?shareId=6cb64e80-01c6-4e78-b9e5-14e4952cbd75).

ci: Fix GitHub action to build for amd and arm architectures and tag latest build with latest

---

README.md

This PR adds a note to the README to warn users to check the disk space available to Docker before creating a new project. Checking the actual disk space available in a cross-platform manner is challenging. Figuring out whether one should check actual disk space or space available to Docker is even more complex.

docs: add disk space warning to README

---

entrypoint.sh

This allows the existing docker-based approach to work on more linux distributions without messing up local permissions. It would probably be better/clearer to actually use `return` statements, but moving the equality operations to the end of the functions also works.

fix: entrypoint.sh: Reorder commands so UID and GID checks work

---

install.sh

resolves #403 
here's how i tested this:
```bash
#!/usr/bin/env bash
echo "testing (part of) scaf installer ensure_bin_folder..."
DUMMY_PATH="/usr/local/bin:/opt/homebrew/sbin:/Users/foo/.pyenv/shims:/usr/bin:/bin:/usr/sbin:/sbin"
if ! [ -n "$DUMMY_PATH" ] && [ -n "$HOME" ] && echo "$DUMMY_PATH" | grep -q ":$HOME/.local/bin:"; then
echo "...current: PASS" # should detect missing $HOME/.local/bin in $PATH
else
echo "...current: FAIL"
fi
if ! [ -n "$NO_PATH" ]; then
echo "...nopath: detected empty path"
else
echo "...nopath: did not detect empty path"
fi
if [ -z "$NO_PATH" ]; then
echo "...linted nopath: detected empty path"
else
echo "...linted nopath: did not detect empty path"
fi
if [ -z "$DUMMY_PATH" ] && [ -z "$NO_HOME" ]; then
echo "...dummypath and nohome: detected empty home"
else …
```

fix: updating tests in install.sh to detect missing preferred bin folder.

---

Dockerfile
entrypoint.sh

Related to #413
Removed extraneous and potentially dangerous operation done in the scaf container
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/sixfeetup/scaf/issues/413?shareId=cdb54542-12a5-45ed-b9f8-838a370755db).

fix: Do not change the ownership of the bind mounted directory

---

{{cookiecutter.project_slug}}/argocd/base/kube-prometheus-stack/app.yaml

This PR enables the retention of Prometheus metrics for ninety days. The default retention period is ten days.

feat: enable prometheus metrics retention for 90 days

---

{{cookiecutter.project_slug}}/docs/development.md

Small change but useful:
Before the next steps came after the dependencies so while going through the first setup, one might miss the next steps, stopping at the dependency update.
Now the sections follow the practical steps one would follow.
Also a couple of small typos fixed.

docs: reorganize next steps and dependencies sections + fix typos

---

{{cookiecutter.project_slug}}/README.md
{{cookiecutter.project_slug}}/docs/qa.md

It was missing. We need a place to store our smoke tests for example.

docs: add qa markdown page

---

.github/workflows/setup-project.yaml

**Overview**
Update setupproject.yaml to init with dev branch

chore: Update workflows to run against dev branch

---

scaf

Ticket: #480
AWS Lambda app template should successfully run through scaf [#480](https://github.com/sixfeetup/scaf/issues/480)
Right now, when a user scaffold AWS Lambda template, it tries to run the default full-stack-template setup on it and errors out.
Scaf is updated so that it can handle aws lambda template and build it
<details>
<summary>What the reviewer should check</summary>
| Check  | Description |
| ------------- | ------------- |
| :truck: **Diff size** | Is the PR small and focused, or should it be broken into smaller PRs?
| :test_tube: **Unit tests** | Are new features covered with appropriate unit tests?
| :lab_coat: **Acceptance Criteria met** | Are the Acceptance Criteria listed in the issue met?
| :monocle_face: **Code clarity** | Is the code easy to understand? Are …

feat: move scaf tasks to corresponding templates #480

---

.github/workflows/semantic-release.yaml

* The deploy key (via SSH) is used for git operations like pushing commits and tags
* The GITHUB_TOKEN is used for API operations like creating releases and commenting on issues

fix: restore semantic release permissions and GITHUB_TOKEN
